# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9841d4ed12bcaf5abb3481a1820b81bdea21a605c20921479386ef456e2b0711b7c4199f31bacccf65bc1e43f2b870c8368ad0080104b0252b05ab6f4d68251

test:
  secret_key_base: 63909c83f8cded4b2031c7a7f1ddb7879810bc9ab4c6df28ba801954475e54ace8c653b67de02bb7b8cc4a35a4a99c3fe3c058405b9aeefbd4a1ea806a9f2707

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
